### PR TITLE
Update to Version 2.0.1

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=635267&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=8437

No PIL installation found
2023-01-02 15:19:51,251:INFO:superset.utils.screenshots:No PIL installation found
Failed to create app
ModuleNotFoundError: No module named 'wtforms.ext'

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
@rxm7706 we have already the version 2.1 released.
I am closing this PR for now
let me know if you really need v2.0.1 and we can discuss how to have that here.

v3.0.1 was already release, if you have time, it would be great to have support for that and any help would be much appreciated.

thanks!

**Pull request closed without merging**
