### PR TITLE
Update RC branch to 0.34.0rc1

### PR DESCRIPTION
**Pull request by sodre**

### CODE REVIEW

**Comment by CurtLH** [comment]
@conda-forge-admin, please rerender

**Review by CurtLH — CHANGES_REQUESTED** [review]
@sodre -- can you update the SHA256?  I would update it myself, but I don't think I can push to your fork.

**Comment by sodre** [comment]
> @sodre -- can you update the SHA256? I would update it myself, but I don't think I can push to your fork.

just did... I think you could have pushed the changes as well. I had the "allow edits from maintainers" turned on.

**Review by CurtLH — APPROVED** [review]

**Comment by CurtLH** [comment]
PR submitted to update source code: https://github.com/apache/incubator-superset/pull/8088

**Comment by sodre** [comment]
Thanks @CurtLH

**Pull request merged**
